### ISSUE TITLE
Submission to the Astro theme portal

### ISSUE THREAD

**Issue by sarah11918** [larry-xue/astro-zen-blog#1]
Hi! I just reviewed your theme submission to Astro and I'm approving it, but wanted to let you know that your listing is not displaying properly, I think because you're using Markdown for your description?

You can see what it looks like here: https://astro.build/themes/details/astro-zen-blog/

I would like your theme to be listed, but wanted to let you know so you could go back and update the listing description so it doesn't look out of place. Unfortunately, you cannot use Markdown in that description as it will not display properly.

Please edit this when you can! Thank you!

**Comment by larry-xue** [comment]
Hi Sarah, thanks for the heads up. I’ve updated the description.
